### PR TITLE
documentation page libertree_philosophy

### PR DESCRIPTION
**Pull request by donnerkarlson**
added first documentation page libertree_philosophy

### CODE REVIEW

**Comment by rekado** [comment]
Thank you very much!  Would you mind renaming the file to "philosophy.markdown"?  I would like to keep the URL short.  Since the page is accessed through Libertree itself I don't think "libertree" needs to be part of the file name.

Also, if you are using Emacs I'd appreciate it if you could break the paragraphs nicely with `M-q` (`Alt-q` or `Alt-x fill-paragraph` with the cursor on the paragraph); but that's just icing on the cake.

**Comment by donnerkarlson** [comment]
i renamed the file, and changed the index.
i don't use emacs, i used the github editor and gedit, i'm not a big shell hacker ;-)

**Comment by rekado** [comment]
Thanks.  I just noticed that this pull request was opened against the "libertree" repository, which is really only used for release synchronisation, not for development.  I will see if I can merge this directly into the "libertree-frontend-ramaze" repository instead.

(PS: I don't use Emacs on the shell.  That would be weird, because Emacs includes multiple shells.)

**Comment by donnerkarlson** [comment]
oh, sorry i did not know where add the request, should i open it for libertree-frontend-ramaze?
@rekado are the markdown changes ok for you?

i've seen emacs only once in a shell tutorial, i didn't know that there is a whole enviroment behind it.

**Comment by rekado** [comment]
> are the markdown changes ok for you?

I'd prefer to only merge your previous changes.  Your changes to the markdown page push down the heading and the introduction text, and they don't add much value in my opinion. 

I would like the internal documentation to be more explanatory than the wiki, i.e. more text and pictures, less of an information dump.

> i've seen emacs only once in a shell tutorial, i didn't know that there is a whole enviroment behind it.

Emacs _is_ the environment `;)`

> oh, sorry i did not know where add the request, should i open it for libertree-frontend-ramaze?

No problem.  In the future, please make pull requests against the individual repositories (libertree-frontend-ramaze-contrib for themes, libertree-frontend-ramaze for everything frontend-related, libertree-backend-rb for the backend, libertree-client-rb for the client library, libertree-db for database schema changes, libertree-model-rb for changes to the database model for ruby code); this time I'll try to apply the patches directly to libertree-frontend-ramaze (outside of Github).

Thanks again!

**Comment by rekado** [comment]
This has been merged into libertree-frontend-ramaze/master.  Closing.

Thanks for your contribution!

**Pull request closed without merging**
